---
abstract: 'Extend File::ShareDir to Local Libraries'
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: File::Share
name: File-Share
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::ShareDir: 1.03
  perl: 5.8.3
resources:
  homepage: http://github.com/ingydotnet/file-share-pm/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ingydotnet/file-share-pm.git
version: 0.02
