---
abstract: 'Extend File::ShareDir to Local Libraries'
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Share
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  File::ShareDir: '1.03'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/file-share-pm/issues
  homepage: https://github.com/ingydotnet/file-share-pm
  repository: https://github.com/ingydotnet/file-share-pm.git
version: '0.14'
